name: international_system_of_units
description: Easily convert unit from and to the international system of units and automatically get the localization for it.
version: 1.0.0-dev
# homepage: https://www.example.com

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  intl: ^0.16.1

dev_dependencies:
  pedantic: ^1.8.0
  intl_translation: ^0.17.10
  test: ^1.14.3
